
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-28T02:24:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7b2975015e7105274b4054e1136a0dfc22361966",
 "version": "1.1.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
