# Generated by Django 5.0 on 2023-12-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("args", models.JSONField()),
                ("kwargs", models.JSONField()),
                ("result", models.JSONField(null=True)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
    ]
