from enum import Enum


class ConnectionState(Enum):
    HELLO_REQUEST = 0
    CLIENT_HELLO = 1
    SERVER_HELLO = 2
    SERVER_CERTIFICATE = 3
    SERVER_KEY_EXCHANGE = 4
    CERTIFICATE_REQUEST = 5
    SERVER_HELLO_DONE = 6
    CLIENT_CERTIFICATE = 7
    CLIENT_KEY_EXCHANGE = 8
    CERTIFICATE_VERIFY = 9
    CLIENT_CHANGE_CIPHER_SPEC = 10
    CLIENT_FINISHED = 11
    SERVER_CHANGE_CIPHER_SPEC = 12
    SERVER_FINISHED = 13
    FLUSH_BUFFERS = 14
    HANDSHAKE_WRAPUP = 15
    HANDSHAKE_OVER = 16
    SERVER_NEW_SESSION_TICKET = 17
    SERVER_HELLO_VERIFY_REQUEST_SENT = 18
