from enum import Enum

# TODO Add all those values http://www.lingoes.net/en/translator/langcode.htm
# TODO We should split between LangCodes which is all lang codes and LangCode which is the Type/Class
# of one lang code
# TODO We need those values in array or other data structure so we can present all lang code in menu,
# so we can link them to country_id, so we can sort by langauge, sort by country ...


class LangCode(Enum):

    HEBREW = 'he'
    HEBREW_ISRAEL = 'he-IL'
    ENGLISH = 'en'
    ENGLISH_UNITED_KINGDOM = 'en-GB'
    ENGLISH_UNITED_STATES = 'en-US'
    ENGLISH_AUSTRALIA = 'en-AU'
    ENGLISH_BELIZE = 'en-BZ'
    ENGLSIH_CANADA = 'en-CA'
    ENGLISH_CARIBBEAN = 'en-CB'
    ENGLISH_IRELAND = 'en-IE'
    ENGLISH_JAMAICA = 'en-JM'
    ENGLISH_NEW_ZEALAND = 'en-NZ'
    ENGLISH_PHILIPPINES = 'en-PH'
    ENGLISH_SOUTH_AFRICA = 'en-ZA'
    ENGLISH_TRINIDAD = 'en-TT'
    ENGLISH_ZIMBABWE = 'en-ZW'
    GERMAN = 'de'
    GERMAN_AUSTRIA = 'de-AT'
    GERMAN_SWITZERLAND = 'de-CH'
    GERMAN_GERMANY = 'de-DE'
    GERMAN_LIECHTENSTEIN = 'de-LI'
    GERMAN_LUXEMBOURG = 'de-LU'
    SPANISH = 'es'
    SPANISH_ARGENTINA = 'es-AR'
    SPANISH_BOLIVIA = 'es-BO'
    SPANISH_CHILE = 'es-CL'
    SPANISH_COLOMBIA = 'es-CO'
    SPANISH_COSTA_RICA = 'es-CR'
    SPANISH_DOMINICAN_REPUBLIC = 'es-DO'
    SPANISH_ECUADOR = 'es-EC'
    SPANISH_SPAIN = 'es-ES'
    SPANISH_GUATEMALA = 'es-GT'
    SPANISH_HONDURAS = 'es-HN'
    SPANISH_MEXICO = 'es-MX'
    SPANISH_NICARAGUA = 'es-NI'
    SPANISH_PANAMA = 'es-PA'
    SPANISH_PERU = 'es-PE'
    SPANISH_PUERTO_RICO = 'es-PR'
    SPANISH_PARAGUAY = 'es-PY'
    SPANISH_EL_SALVADOR = 'es-SV'
    SPANISH_UNITED_STATES = 'es-US'
    SPANISH_URUGUAY = 'es-UY'
    SPANISH_VENEZUELA = 'es-VE'
    FRENCH = 'fr'
    FRENCH_BELGIUM = 'fr-BE'
    FRENCH_CANADA = 'fr-CA'
    FRENCH_FRANCE = 'fr-FR'
    FRENCH_LUXEMBOURG = 'fr-LU'
    FRENCH_MONACO = 'fr-MC'
    FRENCH_SWITZERLAND = 'fr-CH'
    ITALIAN = 'it'
    ITALIAN_SWITZERLAND = 'it-CH'
    ITALIAN_ITALY = 'it-IT'
    DUTCH = 'nl'
    DUTCH_BELGIUM = 'nl-BE'
    DUTCH_NETHERLANDS = 'nl-NL'
