# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from global_vo_grpc_service.protos import review_api_pb2 as global__vo__grpc__service_dot_protos_dot_review__api__pb2


class ReviewApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNextReviewImageByMissionId = channel.unary_unary(
                '/ReviewApi/GetNextReviewImageByMissionId',
                request_serializer=global__vo__grpc__service_dot_protos_dot_review__api__pb2.GetNextReviewImageByMissionIdRequest.SerializeToString,
                response_deserializer=global__vo__grpc__service_dot_protos_dot_review__api__pb2.GetNextReviewImageByMissionIdResponse.FromString,
                )


class ReviewApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNextReviewImageByMissionId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNextReviewImageByMissionId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextReviewImageByMissionId,
                    request_deserializer=global__vo__grpc__service_dot_protos_dot_review__api__pb2.GetNextReviewImageByMissionIdRequest.FromString,
                    response_serializer=global__vo__grpc__service_dot_protos_dot_review__api__pb2.GetNextReviewImageByMissionIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReviewApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReviewApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNextReviewImageByMissionId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ReviewApi/GetNextReviewImageByMissionId',
            global__vo__grpc__service_dot_protos_dot_review__api__pb2.GetNextReviewImageByMissionIdRequest.SerializeToString,
            global__vo__grpc__service_dot_protos_dot_review__api__pb2.GetNextReviewImageByMissionIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
