# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p2p_file_system.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15p2p_file_system.proto\x12\x03p2p\"*\n\x08\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x18\n\x08\x46ileData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\" \n\rShareResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xaa\x01\n\x0eP2PFileService\x12\x30\n\tShareFile\x12\r.p2p.FileInfo\x1a\x12.p2p.ShareResponse\"\x00\x12\x32\n\x0bRequestFile\x12\x10.p2p.FileRequest\x1a\r.p2p.FileData\"\x00\x30\x01\x12\x32\n\nUploadFile\x12\r.p2p.FileInfo\x1a\x13.p2p.UploadResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_file_system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEINFO']._serialized_start=30
  _globals['_FILEINFO']._serialized_end=72
  _globals['_FILEREQUEST']._serialized_start=74
  _globals['_FILEREQUEST']._serialized_end=105
  _globals['_FILEDATA']._serialized_start=107
  _globals['_FILEDATA']._serialized_end=131
  _globals['_SHARERESPONSE']._serialized_start=133
  _globals['_SHARERESPONSE']._serialized_end=165
  _globals['_UPLOADRESPONSE']._serialized_start=167
  _globals['_UPLOADRESPONSE']._serialized_end=200
  _globals['_P2PFILESERVICE']._serialized_start=203
  _globals['_P2PFILESERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
