
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-28T21:58:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c80236cf20a986e0f9b13d3e5611eb91877b9f0",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
