
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-29T18:07:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7724601443312556da72f5c03c623e9be4b4a4e9",
 "version": "3.1.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
