# coding: utf-8

"""
    SEC Search API

    API for receiving classifications of SEC filings.  Note that this API is in  beta and is subject to change before the release of a stable v1.0.0.  By default, the api will return a maximum of 100 results.   To return more results, pass the `page` parameter.   For example, to return the second page of results, pass `page=2`.  <a href=\"https://www.secsearch.io/profile\" target=\"_blank\">Get an API Key</a>   # noqa: E501

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sec_search_client
from sec_search_client.api.entity_api import EntityApi  # noqa: E501
from sec_search_client.rest import ApiException


class TestEntityApi(unittest.TestCase):
    """EntityApi unit test stubs"""

    def setUp(self):
        self.api = EntityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_company_names_entitycompanies_all_get(self):
        """Test case for company_names_entitycompanies_all_get

        Company Names  # noqa: E501
        """
        pass

    def test_get_filings_by_cik_entity_cik_cik_get(self):
        """Test case for get_filings_by_cik_entity_cik_cik_get

        Get Filings By Cik  # noqa: E501
        """
        pass

    def test_search_entities_entity_search_get(self):
        """Test case for search_entities_entity_search_get

        Search Entities  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
