# Generated by Django 4.2.3 on 2023-12-29 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app_model", "0014_dietplancreateoption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplancreateoption",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dietplancreateoption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userdietplancreateoptionrelation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdietplancreateoptionrelation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
