# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_quantum/core/proto/projector_sum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow_quantum/core/proto/projector_sum.proto',
  package='tfq.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n1tensorflow_quantum/core/proto/projector_sum.proto\x12\ttfq.proto\"7\n\x0cProjectorSum\x12\'\n\x05terms\x18\x01 \x03(\x0b\x32\x18.tfq.proto.ProjectorTerm\"z\n\rProjectorTerm\x12\x18\n\x10\x63oefficient_real\x18\x01 \x01(\x02\x12\x18\n\x10\x63oefficient_imag\x18\x02 \x01(\x02\x12\x35\n\x0eprojector_dict\x18\x03 \x03(\x0b\x32\x1d.tfq.proto.ProjectorDictEntry\";\n\x12ProjectorDictEntry\x12\x10\n\x08qubit_id\x18\x01 \x01(\t\x12\x13\n\x0b\x62\x61sis_state\x18\x02 \x01(\x08\x62\x06proto3')
)




_PROJECTORSUM = _descriptor.Descriptor(
  name='ProjectorSum',
  full_name='tfq.proto.ProjectorSum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='terms', full_name='tfq.proto.ProjectorSum.terms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=119,
)


_PROJECTORTERM = _descriptor.Descriptor(
  name='ProjectorTerm',
  full_name='tfq.proto.ProjectorTerm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coefficient_real', full_name='tfq.proto.ProjectorTerm.coefficient_real', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coefficient_imag', full_name='tfq.proto.ProjectorTerm.coefficient_imag', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projector_dict', full_name='tfq.proto.ProjectorTerm.projector_dict', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=243,
)


_PROJECTORDICTENTRY = _descriptor.Descriptor(
  name='ProjectorDictEntry',
  full_name='tfq.proto.ProjectorDictEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qubit_id', full_name='tfq.proto.ProjectorDictEntry.qubit_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='basis_state', full_name='tfq.proto.ProjectorDictEntry.basis_state', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=304,
)

_PROJECTORSUM.fields_by_name['terms'].message_type = _PROJECTORTERM
_PROJECTORTERM.fields_by_name['projector_dict'].message_type = _PROJECTORDICTENTRY
DESCRIPTOR.message_types_by_name['ProjectorSum'] = _PROJECTORSUM
DESCRIPTOR.message_types_by_name['ProjectorTerm'] = _PROJECTORTERM
DESCRIPTOR.message_types_by_name['ProjectorDictEntry'] = _PROJECTORDICTENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProjectorSum = _reflection.GeneratedProtocolMessageType('ProjectorSum', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTORSUM,
  '__module__' : 'tensorflow_quantum.core.proto.projector_sum_pb2'
  # @@protoc_insertion_point(class_scope:tfq.proto.ProjectorSum)
  })
_sym_db.RegisterMessage(ProjectorSum)

ProjectorTerm = _reflection.GeneratedProtocolMessageType('ProjectorTerm', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTORTERM,
  '__module__' : 'tensorflow_quantum.core.proto.projector_sum_pb2'
  # @@protoc_insertion_point(class_scope:tfq.proto.ProjectorTerm)
  })
_sym_db.RegisterMessage(ProjectorTerm)

ProjectorDictEntry = _reflection.GeneratedProtocolMessageType('ProjectorDictEntry', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTORDICTENTRY,
  '__module__' : 'tensorflow_quantum.core.proto.projector_sum_pb2'
  # @@protoc_insertion_point(class_scope:tfq.proto.ProjectorDictEntry)
  })
_sym_db.RegisterMessage(ProjectorDictEntry)


# @@protoc_insertion_point(module_scope)
