# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: global_vo_grpc_service/protos/review_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from global_vo_grpc_service.protos import utils_pb2 as global__vo__grpc__service_dot_protos_dot_utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.global_vo_grpc_service/protos/review_api.proto\x1a)global_vo_grpc_service/protos/utils.proto\"6\n\x19\x43\x61\x63heLastUserQueryRequest\x12\x19\n\x11\x65s_query_json_str\x18\x01 \x01(\t\">\n\x1a\x43\x61\x63heLastUserQueryResponse\x12 \n\x0b\x63hange_type\x18\x01 \x01(\x0e\x32\x0b.ChangeType\"\x87\x01\n\x1a\x43reateMissionReviewRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x15\n\rtotal_batches\x18\x03 \x01(\x05\x12\x12\n\nmission_id\x18\x04 \x01(\x05\x12\x1b\n\x13sample_size_percent\x18\x05 \x01(\x05\"R\n\x1b\x43reateMissionReviewResponse\x12 \n\x0b\x63hange_type\x18\x01 \x01(\x0e\x32\x0b.ChangeType\x12\x11\n\treview_id\x18\x02 \x01(\x05\":\n$GetNextReviewImageByMissionIdRequest\x12\x12\n\nmission_id\x18\x01 \x01(\x05\"9\n%GetNextReviewImageByMissionIdResponse\x12\x10\n\x08image_id\x18\x01 \x01(\x05\x32\x9c\x02\n\tReviewApi\x12M\n\x12\x43\x61\x63heLastUserQuery\x12\x1a.CacheLastUserQueryRequest\x1a\x1b.CacheLastUserQueryResponse\x12P\n\x13\x43reateMissionReview\x12\x1b.CreateMissionReviewRequest\x1a\x1c.CreateMissionReviewResponse\x12n\n\x1dGetNextReviewImageByMissionId\x12%.GetNextReviewImageByMissionIdRequest\x1a&.GetNextReviewImageByMissionIdResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'global_vo_grpc_service.protos.review_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CACHELASTUSERQUERYREQUEST._serialized_start=93
  _CACHELASTUSERQUERYREQUEST._serialized_end=147
  _CACHELASTUSERQUERYRESPONSE._serialized_start=149
  _CACHELASTUSERQUERYRESPONSE._serialized_end=211
  _CREATEMISSIONREVIEWREQUEST._serialized_start=214
  _CREATEMISSIONREVIEWREQUEST._serialized_end=349
  _CREATEMISSIONREVIEWRESPONSE._serialized_start=351
  _CREATEMISSIONREVIEWRESPONSE._serialized_end=433
  _GETNEXTREVIEWIMAGEBYMISSIONIDREQUEST._serialized_start=435
  _GETNEXTREVIEWIMAGEBYMISSIONIDREQUEST._serialized_end=493
  _GETNEXTREVIEWIMAGEBYMISSIONIDRESPONSE._serialized_start=495
  _GETNEXTREVIEWIMAGEBYMISSIONIDRESPONSE._serialized_end=552
  _REVIEWAPI._serialized_start=555
  _REVIEWAPI._serialized_end=839
# @@protoc_insertion_point(module_scope)
