# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataQualityApiServicesExternalAzureModelsBlobFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'absolute_name': 'str',
        'content': 'str',
        'download_url': 'str',
        'web_display_url': 'str'
    }

    attribute_map = {
        'absolute_name': 'absoluteName',
        'content': 'content',
        'download_url': 'downloadUrl',
        'web_display_url': 'webDisplayUrl'
    }

    def __init__(self, absolute_name=None, content=None, download_url=None, web_display_url=None):  # noqa: E501
        """DataQualityApiServicesExternalAzureModelsBlobFile - a model defined in Swagger"""  # noqa: E501
        self._absolute_name = None
        self._content = None
        self._download_url = None
        self._web_display_url = None
        self.discriminator = None
        if absolute_name is not None:
            self.absolute_name = absolute_name
        if content is not None:
            self.content = content
        if download_url is not None:
            self.download_url = download_url
        if web_display_url is not None:
            self.web_display_url = web_display_url

    @property
    def absolute_name(self):
        """Gets the absolute_name of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501


        :return: The absolute_name of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501
        :rtype: str
        """
        return self._absolute_name

    @absolute_name.setter
    def absolute_name(self, absolute_name):
        """Sets the absolute_name of this DataQualityApiServicesExternalAzureModelsBlobFile.


        :param absolute_name: The absolute_name of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501
        :type: str
        """

        self._absolute_name = absolute_name

    @property
    def content(self):
        """Gets the content of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501


        :return: The content of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this DataQualityApiServicesExternalAzureModelsBlobFile.


        :param content: The content of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def download_url(self):
        """Gets the download_url of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501


        :return: The download_url of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501
        :rtype: str
        """
        return self._download_url

    @download_url.setter
    def download_url(self, download_url):
        """Sets the download_url of this DataQualityApiServicesExternalAzureModelsBlobFile.


        :param download_url: The download_url of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501
        :type: str
        """

        self._download_url = download_url

    @property
    def web_display_url(self):
        """Gets the web_display_url of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501


        :return: The web_display_url of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501
        :rtype: str
        """
        return self._web_display_url

    @web_display_url.setter
    def web_display_url(self, web_display_url):
        """Sets the web_display_url of this DataQualityApiServicesExternalAzureModelsBlobFile.


        :param web_display_url: The web_display_url of this DataQualityApiServicesExternalAzureModelsBlobFile.  # noqa: E501
        :type: str
        """

        self._web_display_url = web_display_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataQualityApiServicesExternalAzureModelsBlobFile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataQualityApiServicesExternalAzureModelsBlobFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
