
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-26T18:21:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f781d908cfd98a4b926e9f06c1d0699ec65e21e",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
