# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ColumnStyle(str, enum.Enum):
    """
    An enumeration.
    """

    DEFAULT = "default"
    PRIMARY = "primary"

    def visit(self, default: typing.Callable[[], T_Result], primary: typing.Callable[[], T_Result]) -> T_Result:
        if self is ColumnStyle.DEFAULT:
            return default()
        if self is ColumnStyle.PRIMARY:
            return primary()
