# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'W\xaa\x82\x85'
full_git_hash = '57aa828548f90172e19daea26a2286e2a9308f3e'
git_branch = 'HEAD'
dirty = False
