# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import directory_service_pb2 as directory__service__pb2


class DirectoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateFileLocation = channel.unary_unary(
                '/directory.DirectoryService/UpdateFileLocation',
                request_serializer=directory__service__pb2.FileLocationUpdate.SerializeToString,
                response_deserializer=directory__service__pb2.UpdateResponse.FromString,
                )
        self.GetFileLocations = channel.unary_unary(
                '/directory.DirectoryService/GetFileLocations',
                request_serializer=directory__service__pb2.FileQuery.SerializeToString,
                response_deserializer=directory__service__pb2.FileLocations.FromString,
                )


class DirectoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateFileLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DirectoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateFileLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFileLocation,
                    request_deserializer=directory__service__pb2.FileLocationUpdate.FromString,
                    response_serializer=directory__service__pb2.UpdateResponse.SerializeToString,
            ),
            'GetFileLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileLocations,
                    request_deserializer=directory__service__pb2.FileQuery.FromString,
                    response_serializer=directory__service__pb2.FileLocations.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'directory.DirectoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DirectoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateFileLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/directory.DirectoryService/UpdateFileLocation',
            directory__service__pb2.FileLocationUpdate.SerializeToString,
            directory__service__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/directory.DirectoryService/GetFileLocations',
            directory__service__pb2.FileQuery.SerializeToString,
            directory__service__pb2.FileLocations.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
