"""UntDid1001 BT-3 - Invoice type code
"""
from enum import Enum


class UntDid1001(str, Enum):
    """Enum for all possible values for UNTDID 1001."""

    DEBIT_NOTE_RELATED_TO_GOODS_OR_SERVICES = "80"
    CREDIT_NOTE_RELATED_TO_GOODS_OR_SERVICES = "81"
    METERED_SERVICE_INVOICE = "82"
    CREDIT_NOTE_RELATED_TO_FINANCIAL_ADJUSTMENTS = "83"
    DEBIT_NOTE_RELATED_TO_FINANCIAL_ADJUSTMENTS = "84"
    INVOICING_DATA_SHEED = "130"
    DIRECT_PAYMENT_VALUATION = "202"
    PROVISIONAL_PAYMENT_VALUATION = "203"
    PAYMENT_VALUATION = "204"
    INTERIM_APPLICATION_FOR_PAYMENT = "211"
    ORDER = "220"  # order-x
    ORDER_CHANGE = "230"  # order-x
    ORDER_RESPONSE = "231"  # order-x
    SELF_BILLED_CREDIT_NOTE = "261"
    CONSOLIDATED_CREDIT_NOTE_GOODS_AND_SERVICES = "262"
    PRICE_VARIATION_INVOICE = "295"
    CREDIT_NOTE_FOR_PRICE_VARIATION = "296"
    DELCREDERE_CREDIT_NOTE = "308"
    PROFORMA_INVOICE = "325"
    PARTIAL_INVOICE = "326"
    COMMERICAL_INVOICE = "380"  # standard !!
    CREDIT_NOTE = "381"  # standard !!
    DEBIT_NOTE = "383"
    CORRECTED_INVOICE = "384"
    PREPAYMENT_INVOICE = "386"
    HIRE_INVOICE = "387"
    TAX_INVOICE = "388"
    SELF_BILLED_INVOICE = "389"  # created by the buyer on behalf of the supplier
    DELCREDERE_INVOICE = "390"
    FACTORED_INVOICE = "393"
    LEASE_INVOICE = "394"
    CONSIGNMENT_INVOICE = "395"
    FACTORED_CREDIT_NOTE = "396"
    OCR_PAYMENT_CREDIT_NOTE = "420"
    DEBIT_ADVICE = "456"
    REVERSAL_OF_DEBIT = "457"
    REVERSAL_OF_CREDIT = "458"
    SELF_BILLED_DEBIT_NOTE = "527"
    INSURERS_INVOICE = "575"
    FORWARDERS_INVOICE = "623"
    PORT_CHARGES_DOCUMENTS = "633"
    INVOICE_INFORMATION_FOR_ACCOUNTING_PURPOSES = "751"
    FREIGHT_INVOICE = "780"
    CUSTOMS_INVOICE = "935"
