# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HelpersModelDataBricksClusterInitScript(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'workspace': 'HelpersModelDataBricksClusterFileLocation',
        'dbfs': 'MicrosoftAzureDatabricksClientModelsDbfsStorageInfo'
    }

    attribute_map = {
        'workspace': 'workspace',
        'dbfs': 'dbfs'
    }

    def __init__(self, workspace=None, dbfs=None):  # noqa: E501
        """HelpersModelDataBricksClusterInitScript - a model defined in Swagger"""  # noqa: E501
        self._workspace = None
        self._dbfs = None
        self.discriminator = None
        if workspace is not None:
            self.workspace = workspace
        if dbfs is not None:
            self.dbfs = dbfs

    @property
    def workspace(self):
        """Gets the workspace of this HelpersModelDataBricksClusterInitScript.  # noqa: E501


        :return: The workspace of this HelpersModelDataBricksClusterInitScript.  # noqa: E501
        :rtype: HelpersModelDataBricksClusterFileLocation
        """
        return self._workspace

    @workspace.setter
    def workspace(self, workspace):
        """Sets the workspace of this HelpersModelDataBricksClusterInitScript.


        :param workspace: The workspace of this HelpersModelDataBricksClusterInitScript.  # noqa: E501
        :type: HelpersModelDataBricksClusterFileLocation
        """

        self._workspace = workspace

    @property
    def dbfs(self):
        """Gets the dbfs of this HelpersModelDataBricksClusterInitScript.  # noqa: E501


        :return: The dbfs of this HelpersModelDataBricksClusterInitScript.  # noqa: E501
        :rtype: MicrosoftAzureDatabricksClientModelsDbfsStorageInfo
        """
        return self._dbfs

    @dbfs.setter
    def dbfs(self, dbfs):
        """Sets the dbfs of this HelpersModelDataBricksClusterInitScript.


        :param dbfs: The dbfs of this HelpersModelDataBricksClusterInitScript.  # noqa: E501
        :type: MicrosoftAzureDatabricksClientModelsDbfsStorageInfo
        """

        self._dbfs = dbfs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HelpersModelDataBricksClusterInitScript, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HelpersModelDataBricksClusterInitScript):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
