# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_call.ipynb.

# %% auto 0
__all__ = ['getlocalskw', 'getcallattrs']

# %% ../nbs/02_call.ipynb 6
from functools import wraps

# %% ../nbs/02_call.ipynb 8
#| export


# %% ../nbs/02_call.ipynb 10
#| export


# %% ../nbs/02_call.ipynb 12
from chck import notnone
from nlit import KWARGS

# %% ../nbs/02_call.ipynb 14
#| export


# %% ../nbs/02_call.ipynb 16
def getlocalskw(k, **kwargs): 
    return locals().get(KWARGS, {}).get(k, None) or kwargs.get(k, None)

def getcallattrs(*attrs, **kwargs):
    return dict((a, v) for a in attrs if notnone(v := getlocalskw(a, **kwargs)))
