# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class KeyType(str, enum.Enum):
    """
    All possible key types
    """

    GCS = "GCS"
    AWS = "AWS"

    def visit(self, gcs: typing.Callable[[], T_Result], aws: typing.Callable[[], T_Result]) -> T_Result:
        if self is KeyType.GCS:
            return gcs()
        if self is KeyType.AWS:
            return aws()
