LIGHTHOUSE_URL = 'wss://lighthouse.uni-kiel.de/websocket'
LIGHTHOUSE_ROWS = 14
LIGHTHOUSE_COLS = 28
LIGHTHOUSE_COLOR_CHANNELS = 3
LIGHTHOUSE_FRAME_SHAPE = (LIGHTHOUSE_ROWS, LIGHTHOUSE_COLS, LIGHTHOUSE_COLOR_CHANNELS)
