
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-29T11:58:30+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ffee492d79c1bf9a6bdef8291dc0a56117abe06",
 "version": "0.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
