"""
    Red Rover API

    Access Red Rover data via this REST API for Organizations that have granted you access.  # Authentication The API is protected by HTTP Basic Authentication.   Each application that connects to the API has a unique username and password that it must supply with every request.  This value needs to be supplied as an HTTP Header: `Authorization=BASIC [hash]`. The value of [hash] is the string username:password base64 encoded.  Endpoints marked for Basic Auth can be used with the Basic Auth username and password that you have been assigned.  # API Information ## Api Key Each Red Rover organization that has authorized your application has a unique API Key for your application.  To retrieve the API Key, you can use the Organization endpoint (`api/v1/organization`) which returns an ApiKey uniquely used for each Organization.  You must supply this as an HTTP Header when accessing that organization: `apiKey=[apiKey]`. The domains that require this `ApiKey` header are labeled as 'Requires an ApiKey'.  ## Identifier Where an `Identifier` can be specified in the route, you may either supply the Red Rover Id of the object (numeric) or the External Id (alpha-numeric). When specifying an External Id, you will need to prepend the External Id with the pike character`|` (e.g. `|ABC123`). Please note that this is only the case when the External Id is within the route. If the External Id is contained within the body of the request, do not append the pike character.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: dev@redroverk12.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import redrover_api
from redrover_api.model.accounting_code_allocation_response import AccountingCodeAllocationResponse
from redrover_api.model.approval_status_enum import ApprovalStatusEnum
from redrover_api.model.int32_id_name_class import Int32IdNameClass
from redrover_api.model.pay_code_response import PayCodeResponse
from redrover_api.model.simple_person import SimplePerson
globals()['AccountingCodeAllocationResponse'] = AccountingCodeAllocationResponse
globals()['ApprovalStatusEnum'] = ApprovalStatusEnum
globals()['Int32IdNameClass'] = Int32IdNameClass
globals()['PayCodeResponse'] = PayCodeResponse
globals()['SimplePerson'] = SimplePerson
from redrover_api.model.vacancy_detail_response import VacancyDetailResponse


class TestVacancyDetailResponse(unittest.TestCase):
    """VacancyDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVacancyDetailResponse(self):
        """Test VacancyDetailResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VacancyDetailResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
