"""empty message

Revision ID: ca72d84f7d8b
Revises: d14fae4eb0f7
Create Date: 2023-11-14 12:20:16.748517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca72d84f7d8b'
down_revision = 'd14fae4eb0f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('linked_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['linked_user_id'], ['fansly.users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['fansly.x_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fansly'
    )
    op.create_table('linked_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('linked_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['linked_user_id'], ['onlyfans.users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['onlyfans.x_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='onlyfans'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linked_users', schema='onlyfans')
    op.drop_table('linked_users', schema='fansly')
    # ### end Alembic commands ###
