# Generated by Django 4.1.7 on 2023-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox_hitcount', '0004_alter_hitbrowser_version_alter_hitdevice_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitbrowser',
            name='version',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hitdevice',
            name='version',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hitos',
            name='version',
            field=models.CharField(max_length=30),
        ),
    ]
