
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-29T17:07:55+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f83892d421998d63e76720eb7a3757678285dc7",
 "version": "0.7.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
