
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-25T22:25:03+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "d27f445c5cc1b1720e31963f911d35f8737b7c70",
 "version": "0.1.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
