# Generated by Django 4.1.7 on 2023-03-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox_hitcount', '0010_hitcount_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlocation',
            name='city',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hitlocation',
            name='country',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
