# Autogenerated by devscripts/update-version.py

__version__ = '2023.12.31.232713'

RELEASE_GIT_HEAD = '85a2d07c1f82c2082b568963d1c32ad3fc848f61'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2023.12.31.232713dev'
