# import re-usable tools:
from .Tools.AlineasPresent import AlineasPresent
from .Tools.ByteComparison import ByteComparison
from .Tools.CodeCoverage import CodeCoverage
from .Tools.CompareImages import CompareImages
from .Tools.CompareTexts import CompareTexts
from .Tools.DjangoCoverage import DjangoCoverage
from .Tools.FileComparison import FileComparison
from .Tools.ImgRMS import ImgRMS
from .Tools.Platformdetection import MySystem
from .Tools.Platformdetection import detectsystem
from .Tools.ReplaceTextInFile import ReplaceTextInFile
