from kink import di
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain.tools import tool
from langchain.schema.runnable import RunnablePassthrough
from langchain.schema.output_parser import StrOutputParser
from langchain.prompts.prompt import PromptTemplate

SELF_GENERATED_COT_TEMPLATE = """
## Question: {question}
## Answer: {answer}
Given the above question and answer, generate a chain of thought explanation for the answer.
First, start with the model generated chain of thought explanation.
End the chain of though explanation with:
Therefore, the answer is {answer}.
"""

SELF_GENERATED_COT_PROMPT = PromptTemplate.from_template(SELF_GENERATED_COT_TEMPLATE)

self_gen_cot_llm = di["self_gen_cot_llm"]

class SelfGenCot(BaseModel):
    question: str = Field()
    answer: str = Field()

def get_runnable(**kwargs):
    """Get the runnable chain."""
    _cot = RunnablePassthrough.assign(
        question = lambda x: x["question"],
        answer = lambda x: x["answer"],
        ) | SELF_GENERATED_COT_PROMPT | self_gen_cot_llm | StrOutputParser()
    chain = _cot.with_types(input_type=SelfGenCot)
    return chain

@tool("self generated explanation", args_schema=SelfGenCot)
def get_sgc_tool(**kwargs):
    """
    Returns the self generated chain of thought explanation for the given question and answer.

    Args:
        question (str): The question asked to the model.
        answer (str): The answer generated by the model.
    """
    return get_runnable().invoke(kwargs)