# Generated by Django 5.0 on 2023-12-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
