""".

Revision ID: 2dde7648bb3f
Revises: 7df91f723f2d
Create Date: 2023-10-09 16:02:07.778312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2dde7648bb3f"
down_revision: Union[str, None] = "7df91f723f2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("controllers", schema=None) as batch_op:
        batch_op.create_unique_constraint("uix_cont_1", ["ip", "mid"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("controllers", schema=None) as batch_op:
        batch_op.drop_constraint("uix_cont_1", type_="unique")

    # ### end Alembic commands ###
