""".

Revision ID: 7df91f723f2d
Revises: f8838525b28f
Create Date: 2023-10-09 15:56:58.063962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7df91f723f2d"
down_revision: Union[str, None] = "f8838525b28f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("controllers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_controllers_ip"), ["ip"], unique=True)
        batch_op.create_index(batch_op.f("ix_controllers_mid"), ["mid"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("controllers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_controllers_mid"))
        batch_op.drop_index(batch_op.f("ix_controllers_ip"))

    # ### end Alembic commands ###
