# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AppsRegistryAppFullDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'application_display_name': 'str',
        'description': 'str',
        'image_url': 'str',
        'owner': 'OwnerOwnerDto',
        'detail': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'application_display_name': 'applicationDisplayName',
        'description': 'description',
        'image_url': 'imageUrl',
        'owner': 'owner',
        'detail': 'detail'
    }

    def __init__(self, id=None, name=None, application_display_name=None, description=None, image_url=None, owner=None, detail=None):  # noqa: E501
        """AppsRegistryAppFullDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._application_display_name = None
        self._description = None
        self._image_url = None
        self._owner = None
        self._detail = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if application_display_name is not None:
            self.application_display_name = application_display_name
        if description is not None:
            self.description = description
        if image_url is not None:
            self.image_url = image_url
        if owner is not None:
            self.owner = owner
        if detail is not None:
            self.detail = detail

    @property
    def id(self):
        """Gets the id of this AppsRegistryAppFullDto.  # noqa: E501


        :return: The id of this AppsRegistryAppFullDto.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AppsRegistryAppFullDto.


        :param id: The id of this AppsRegistryAppFullDto.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AppsRegistryAppFullDto.  # noqa: E501


        :return: The name of this AppsRegistryAppFullDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AppsRegistryAppFullDto.


        :param name: The name of this AppsRegistryAppFullDto.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def application_display_name(self):
        """Gets the application_display_name of this AppsRegistryAppFullDto.  # noqa: E501


        :return: The application_display_name of this AppsRegistryAppFullDto.  # noqa: E501
        :rtype: str
        """
        return self._application_display_name

    @application_display_name.setter
    def application_display_name(self, application_display_name):
        """Sets the application_display_name of this AppsRegistryAppFullDto.


        :param application_display_name: The application_display_name of this AppsRegistryAppFullDto.  # noqa: E501
        :type: str
        """

        self._application_display_name = application_display_name

    @property
    def description(self):
        """Gets the description of this AppsRegistryAppFullDto.  # noqa: E501


        :return: The description of this AppsRegistryAppFullDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AppsRegistryAppFullDto.


        :param description: The description of this AppsRegistryAppFullDto.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def image_url(self):
        """Gets the image_url of this AppsRegistryAppFullDto.  # noqa: E501


        :return: The image_url of this AppsRegistryAppFullDto.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this AppsRegistryAppFullDto.


        :param image_url: The image_url of this AppsRegistryAppFullDto.  # noqa: E501
        :type: str
        """

        self._image_url = image_url

    @property
    def owner(self):
        """Gets the owner of this AppsRegistryAppFullDto.  # noqa: E501


        :return: The owner of this AppsRegistryAppFullDto.  # noqa: E501
        :rtype: OwnerOwnerDto
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this AppsRegistryAppFullDto.


        :param owner: The owner of this AppsRegistryAppFullDto.  # noqa: E501
        :type: OwnerOwnerDto
        """

        self._owner = owner

    @property
    def detail(self):
        """Gets the detail of this AppsRegistryAppFullDto.  # noqa: E501


        :return: The detail of this AppsRegistryAppFullDto.  # noqa: E501
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this AppsRegistryAppFullDto.


        :param detail: The detail of this AppsRegistryAppFullDto.  # noqa: E501
        :type: str
        """

        self._detail = detail

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AppsRegistryAppFullDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppsRegistryAppFullDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
