
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-31T22:08:25+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "81ca23014b10ffe9e79cea619a4011e693ace48c",
 "version": "1.65.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
