
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-24T02:14:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "18298975fb8afe7eb7bc626d432102946638eda2",
 "version": "1.4.dev2352"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
